# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-10f458a0-90f9-4be7-8123-eb899bc60852";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-10f458a0-90f9-4be7-8123-eb899bc60852".device = "/dev/disk/by-uuid/10f458a0-90f9-4be7-8123-eb899bc60852";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FE63-8CB6";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-5d12f2b1-766f-45a6-847c-ad23b23cbedc"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
