# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-dbe04df5-db7e-40ee-a431-cf37be49bcd1";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-dbe04df5-db7e-40ee-a431-cf37be49bcd1".device = "/dev/disk/by-uuid/dbe04df5-db7e-40ee-a431-cf37be49bcd1";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B76B-B01B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-7523f139-ce39-4d41-9c81-2279bc723855"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
